### ISSUE TITLE
Add a RESTful sensor to Home Assistant

### ISSUE THREAD

**Issue by romquenin** [xnekv03/nameday-api#91]
Hello, i would like to add a RESTful sensor to my domotic system Home Assistant to be able to display only the French name day.

Unfortunately i can't find the proper code to get the name day:

```
- platform: rest
  resource: https://nameday.abalin.net/api/V2/today/
  method: POST
  name: Name Day
  payload: '{ "country" : "fr" }'
```

Do you please know what should i input in the payload section?

Thanks in advance

**Comment by laczynskik** [comment]
Hello, you can use following template:

```
  - platform: rest
    name: Name Day
    method: GET
    resource: https://nameday.abalin.net/api/V2/today/UTC
    value_template: "{{ value_json.data.fr }}"
    headers:
      Accept: application/json
```
